#!/usr/bin/env python3
"""Generate po/server_strings.h from mayara-server's docs/ui-strings.json.

The control names and enum labels in the radar schema are English literals in
mayara-server. That repo publishes them as docs/ui-strings.json; this script
turns the file into wxTRANSLATE markers so xgettext puts them in our .pot and
ServerText.cpp can look them up at run time. The header is never compiled.

Which server version to read is pinned in po/server-strings.ref (a tag, branch
or commit of MarineYachtRadar/mayara-server). Bump it, run this, then run the
mayara-pot-update target.

  tools/gen-server-strings.py                 # fetch the pinned ref, rewrite
  tools/gen-server-strings.py --json FILE     # use a local ui-strings.json
  tools/gen-server-strings.py --check         # exit 1 if the header is stale
"""

import argparse
import json
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
REF_FILE = ROOT / "po" / "server-strings.ref"
OUT_FILE = ROOT / "po" / "server_strings.h"
URL = ("https://raw.githubusercontent.com/MarineYachtRadar/mayara-server/"
       "{ref}/docs/ui-strings.json")


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(data, ref):
    lines = [
        "// Generated by tools/gen-server-strings.py from mayara-server's",
        f"// docs/ui-strings.json at {ref}.",
        "// Do not edit. Not compiled, only read by xgettext; see",
        "// include/ServerText.h.",
        "",
        "// Control names.",
    ]
    for name in sorted({c["name"] for c in data["controls"] if c["name"]}):
        lines.append(f"wxTRANSLATE({c_string(name)})")
    lines += ["", "// Enum labels, in the context of the control they belong to."]
    for e in sorted(data["enums"], key=lambda e: e["control"]):
        for label in sorted(set(e["labels"])):
            lines.append(f"wxTRANSLATE_IN_CONTEXT({c_string(e['control'])}, "
                         f"{c_string(label)})")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--json", help="local ui-strings.json instead of fetching")
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if the header is out of date")
    args = ap.parse_args()

    ref = REF_FILE.read_text(encoding="utf-8").strip()
    if args.json:
        data = json.loads(pathlib.Path(args.json).read_text(encoding="utf-8"))
    else:
        with urllib.request.urlopen(URL.format(ref=ref), timeout=30) as r:
            data = json.load(r)

    text = render(data, ref)
    if args.check:
        current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else ""
        if current != text:
            print(f"{OUT_FILE.relative_to(ROOT)} is out of date for "
                  f"mayara-server {ref}; run tools/gen-server-strings.py",
                  file=sys.stderr)
            return 1
        return 0
    OUT_FILE.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
