/******************************************************************************
 * mayara_pi - OpenCPN plugin for mayara-server.
 *****************************************************************************/
#include "mayara_pi.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>

#include <wx/bmpbndl.h>
#include <wx/dcmemory.h>
#include <wx/display.h>
#include <wx/fileconf.h>
#include <wx/spinctrl.h>
#include <wx/toplevel.h>

#ifdef __WXOSX__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif

#include "MayaraClient.h"
#include "MayaraTheme.h"
#include "PpiWindow.h"
#include "RadarState.h"
#include "version.h"  // generated by FE2 from CMakeLists.txt values

// Map an OpenCPN colour scheme to the plugin's UI theme.
static MayaraTheme ThemeFor(PI_ColorScheme cs) {
  MayaraTheme t;  // day / RGB defaults
  switch (cs) {
    case PI_GLOBAL_COLOR_SCHEME_NIGHT:
      t.panel_bg = wxColour(18, 6, 6);
      t.text = wxColour(190, 90, 90);
      t.dim_text = wxColour(120, 60, 60);
      t.lozenge_bg = wxColour(28, 10, 10);
      t.lozenge_border = wxColour(90, 40, 40);
      t.accent = wxColour(215, 80, 80);
      t.accent_dim = wxColour(150, 70, 60);
      t.radar_intensity = 0.5f;
      break;
    case PI_GLOBAL_COLOR_SCHEME_DUSK:
      t.panel_bg = wxColour(20, 20, 26);
      t.text = wxColour(165, 165, 175);
      t.dim_text = wxColour(110, 110, 120);
      t.lozenge_bg = wxColour(22, 22, 28);
      t.lozenge_border = wxColour(70, 70, 80);
      t.accent = wxColour(110, 190, 110);
      t.accent_dim = wxColour(175, 155, 95);
      t.radar_intensity = 0.72f;
      break;
    default:
      break;  // day/rgb use the struct defaults
  }
  return t;
}

// mayara-server is normally found via mDNS (it advertises _signalk-http._tcp).
// MAYARA_SERVER forces a specific address; kMayaraServerFallback is used only
// if discovery finds nothing.
static const char* kMayaraServerFallback = "http://10.56.0.1:6502";

static std::string MayaraExplicitUrl() {
  const char* env = std::getenv("MAYARA_SERVER");
  return (env && *env) ? std::string(env) : std::string();
}

// The two factory functions OpenCPN's PluginManager dlsym()s to load us.
extern "C" DECL_EXP opencpn_plugin* create_pi(void* ppimgr) {
  return new mayara_pi(ppimgr);
}

extern "C" DECL_EXP void destroy_pi(opencpn_plugin* p) { delete p; }

// Radar / PPI glyph with a transparent background and light strokes, matching
// the OpenCPN toolbar. Embedded and rasterized in-process so the plugin needs
// no shipped image files (and can be updated by replacing the .dylib alone).
static const char kRadarSvg[] =
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' "
    "stroke='#e8e8e8' stroke-width='1.6' stroke-linecap='round' "
    "stroke-linejoin='round'>"
    "<circle cx='12' cy='12' r='9.5'/>"
    "<circle cx='12' cy='12' r='6'/>"
    "<circle cx='12' cy='12' r='2.3'/>"
    "<path d='M12 12 L12 2.5 A9.5 9.5 0 0 1 20.4 7.2 Z' fill='#e8e8e8' "
    "fill-opacity='0.25' stroke='none'/>"
    "<line x1='12' y1='12' x2='12' y2='2.5'/>"
    "<circle cx='16' cy='8' r='1.1' fill='#e8e8e8' stroke='none'/>"
    "</svg>";

static wxBitmap RadarIcon(int px) {
  wxBitmapBundle bb = wxBitmapBundle::FromSVG(kRadarSvg, wxSize(px, px));
  if (bb.IsOk()) return bb.GetBitmap(wxSize(px, px));
  return wxBitmap(px, px, 32);  // transparent fallback
}

mayara_pi::mayara_pi(void* ppimgr) : opencpn_plugin_121(ppimgr) {
  m_panel_bitmap = RadarIcon(48);
  m_tool_bitmap = RadarIcon(32);
}

mayara_pi::~mayara_pi() = default;

int mayara_pi::Init() {
  m_parent_window = GetOCPNCanvasWindow();
  LoadConfig();

  m_tool_id = InsertPlugInTool(
      _("Mayara"), &m_tool_bitmap, &m_tool_bitmap, wxITEM_CHECK,
      _("Mayara Radar"), _("Show or hide the Mayara radar PPI window"),
      nullptr, -1, 0, this);

  // Canvas right-click context-menu items (checkable), mirroring radar_pi.
  {
    m_mi_overlay_item = new wxMenuItem(
        nullptr, wxID_ANY, _("Mayara radar overlay"), wxEmptyString,
        wxITEM_CHECK);
    m_mi_overlay = AddCanvasContextMenuItem(m_mi_overlay_item, this);
    m_mi_ppi_item = new wxMenuItem(nullptr, wxID_ANY, _("Mayara PPI window"),
                                   wxEmptyString, wxITEM_CHECK);
    m_mi_ppi = AddCanvasContextMenuItem(m_mi_ppi_item, this);
  }

  m_client = std::make_unique<MayaraClient>(MayaraExplicitUrl(),
                                            kMayaraServerFallback);
  m_client->Start();

  // Capabilities. The overlay callback is declared now but returns false until
  // Phase 1 wires up the spoke renderer.
  return WANTS_OPENGL_OVERLAY_CALLBACK | WANTS_OVERLAY_CALLBACK |
         WANTS_TOOLBAR_CALLBACK | INSTALLS_TOOLBAR_TOOL | WANTS_CURSOR_LATLON |
         WANTS_PREFERENCES;
}

bool mayara_pi::DeInit() {
  // Destroy the window first (synchronously) so its panels' timers stop calling
  // into the client before we free it.
  DestroyWindows(/*sync=*/true);
  if (m_tool_id != -1) {
    RemovePlugInTool(m_tool_id);
    m_tool_id = -1;
  }
  if (m_mi_overlay != -1) RemoveCanvasContextMenuItem(m_mi_overlay);
  if (m_mi_ppi != -1) RemoveCanvasContextMenuItem(m_mi_ppi);
  m_mi_overlay = m_mi_ppi = -1;
  if (m_client) {
    m_client->Stop();
    m_client.reset();
  }
  // Drain any pending (possibly cross-thread) log records now, while this
  // plugin's dylib -- and the string literals its log records point at -- is
  // still mapped. Otherwise OpenCPN flushes them on a later idle tick after
  // unloading us, dereferencing freed memory in OcpnLog::DoLogRecord.
  wxLog::FlushActive();
  return true;
}

// --- Preferences / settings ------------------------------------------------

static const char* kConfigGroup = "/PlugIns/mayara";

void mayara_pi::LoadConfig() {
  wxFileConfig* cfg = GetOCPNConfigObject();
  if (!cfg) return;
  cfg->SetPath(kConfigGroup);
  int windows = 1;
  cfg->Read("WindowsCount", &windows, 1);
  m_windows_count = windows < 1 ? 1 : windows;
  bool overlay = true;
  cfg->Read("OverlayEnabled", &overlay, true);
  m_overlay_enabled = overlay;
}

void mayara_pi::SaveConfig() {
  wxFileConfig* cfg = GetOCPNConfigObject();
  if (!cfg) return;
  cfg->SetPath(kConfigGroup);
  cfg->Write("WindowsCount", m_windows_count);
  cfg->Write("OverlayEnabled", m_overlay_enabled);
  cfg->Flush();
}

// OpenCPN's "Preferences" button in the plugin manager routes here; our own
// gear button routes here too. Both hand us a parent to centre on.
void mayara_pi::ShowPreferencesDialog(wxWindow* parent) { ShowSettings(parent); }

void mayara_pi::ShowSettings(wxWindow* parent) {
  const int radar_count = m_client ? m_client->RadarCount() : 0;
  // With N radars you can spread them across 1..N windows; the per-window count
  // is N / windows (rounded up). Cap the spinner sensibly when nothing is found.
  const int max_windows = radar_count > 0 ? radar_count : 4;

  wxDialog dlg(parent, wxID_ANY, _("Mayara Radar Settings"), wxDefaultPosition,
               wxDefaultSize, wxDEFAULT_DIALOG_STYLE);
  auto* top = new wxBoxSizer(wxVERTICAL);

  wxString summary =
      radar_count > 0
          ? wxString::Format(_("%d radar(s) discovered."), radar_count)
          : _("No radars discovered yet.");
  top->Add(new wxStaticText(&dlg, wxID_ANY, summary), 0, wxALL, 10);

  auto* row = new wxBoxSizer(wxHORIZONTAL);
  row->Add(new wxStaticText(&dlg, wxID_ANY, _("Number of PPI windows:")), 0,
           wxALIGN_CENTER_VERTICAL | wxRIGHT, 8);
  auto* spin = new wxSpinCtrl(&dlg, wxID_ANY, wxEmptyString, wxDefaultPosition,
                              wxDefaultSize, wxSP_ARROW_KEYS, 1, max_windows,
                              m_windows_count);
  row->Add(spin, 0, wxALIGN_CENTER_VERTICAL);
  top->Add(row, 0, wxLEFT | wxRIGHT | wxBOTTOM, 10);

  auto* hint = new wxStaticText(
      &dlg, wxID_ANY,
      _("Radars are spread evenly across the windows. One window shows all "
        "radars; more windows split them (e.g. 8 radars across 2 windows = 4 "
        "per window)."));
  hint->Wrap(360);
  top->Add(hint, 0, wxLEFT | wxRIGHT | wxBOTTOM, 10);

  top->Add(dlg.CreateButtonSizer(wxOK | wxCANCEL), 0,
           wxALIGN_RIGHT | wxALL, 10);
  dlg.SetSizerAndFit(top);

  if (dlg.ShowModal() == wxID_OK) {
    const int chosen = spin->GetValue();
    if (chosen != m_windows_count) {
      m_windows_count = chosen;
      SaveConfig();
      // Re-lay-out the radars across the new number of windows, keeping the
      // current show/hide intent.
      if (!m_windows.empty() || m_windows_visible) RebuildWindows();
    }
  }
}

int mayara_pi::GetAPIVersionMajor() { return OCPN_API_VERSION_MAJOR; }
int mayara_pi::GetAPIVersionMinor() { return OCPN_API_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionMajor() { return PLUGIN_VERSION_MAJOR; }
int mayara_pi::GetPlugInVersionMinor() { return PLUGIN_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionPatch() { return PLUGIN_VERSION_PATCH; }

wxBitmap* mayara_pi::GetPlugInBitmap() { return &m_panel_bitmap; }

wxString mayara_pi::GetCommonName() { return _T("Mayara"); }

wxString mayara_pi::GetShortDescription() {
  return _("Marine radar overlay and PPI, served by mayara-server");
}

wxString mayara_pi::GetLongDescription() {
  return _(
      "mayara_pi displays marine radar as a chart overlay and in a PPI "
      "window. Unlike radar_pi it does not talk to radar hardware directly; "
      "it consumes the mayara-server REST and WebSocket API.");
}

int mayara_pi::GetToolbarToolCount() { return 1; }

void mayara_pi::OnToolbarToolCallback(int id) {
  if (id == m_tool_id) TogglePpiWindow();
}

void mayara_pi::OnContextMenuItemCallback(int id) {
  if (id == m_mi_overlay) {
    m_overlay_enabled = !m_overlay_enabled;
    SaveConfig();
    GetOCPNCanvasWindow()->Refresh(false);
  } else if (id == m_mi_ppi) {
    TogglePpiWindow();
  }
}

// Called just before the canvas context menu is shown; sync the check marks
// to the live state.
void mayara_pi::PrepareContextMenu(int /*canvasIndex*/) {
  if (m_mi_overlay_item) m_mi_overlay_item->Check(m_overlay_enabled);
  if (m_mi_ppi_item)
    m_mi_ppi_item->Check(AnyWindowShown());
}

// Split the discovered radars into m_windows_count near-even groups. Window w
// gets radars [w*base + min(w,rem) ..], distributing the remainder to the first
// windows. Never more windows than radars.
std::vector<std::vector<int>> mayara_pi::RadarGroups() const {
  std::vector<std::vector<int>> groups;
  const int n = m_client ? m_client->RadarCount() : 0;
  if (n <= 0) return groups;
  const int w = std::max(1, std::min(m_windows_count, n));
  const int base = n / w, rem = n % w;
  int idx = 0;
  for (int g = 0; g < w; ++g) {
    const int count = base + (g < rem ? 1 : 0);
    std::vector<int> grp;
    for (int k = 0; k < count; ++k) grp.push_back(idx++);
    groups.push_back(std::move(grp));
  }
  return groups;
}

void mayara_pi::DestroyWindows(bool sync) {
  for (MayaraPpiWindow* win : m_windows) {
    if (!win) continue;
    win->Hide();
    // sync: delete now, so panel timers can't call into a freed client during
    // plugin teardown. async: defer (we may be inside a window's own handler,
    // e.g. its gear button); the client is still alive, so timers are safe.
    if (sync)
      delete win;
    else
      win->Destroy();
  }
  m_windows.clear();
}

bool mayara_pi::AnyWindowShown() const {
  for (MayaraPpiWindow* win : m_windows)
    if (win && win->IsShown()) return true;
  return false;
}

void mayara_pi::ApplyThemeToWindows() {
  for (MayaraPpiWindow* win : m_windows)
    if (win) win->ApplyTheme(ThemeFor(m_color_scheme));
}

// (Re)create the radar windows from the current radar count and window count,
// preserving the user's show/hide intent.
void mayara_pi::RebuildWindows() {
  DestroyWindows(/*sync=*/false);
  m_windows_radar_count = m_client ? m_client->RadarCount() : 0;
  std::vector<std::vector<int>> groups = RadarGroups();
  // No radars yet: still open one window bound to index 0 so the user sees the
  // "waiting for radar" UI; it starts showing radar 0 as soon as it connects.
  if (groups.empty()) groups.push_back({0});
  for (const std::vector<int>& grp : groups) {
    auto* win = new MayaraPpiWindow(m_parent_window, m_client.get(), grp);
    win->ApplyTheme(ThemeFor(m_color_scheme));
    win->SetOverlayControl([this]() { return m_overlay_enabled; },
                           [this](bool on) {
                             m_overlay_enabled = on;
                             SaveConfig();
                             GetOCPNCanvasWindow()->Refresh(false);
                           });
    win->SetSettingsControl([this, win]() { ShowSettings(win); });
    win->SetAutoLayoutControl([this]() { AutoLayoutWindows(/*reflow=*/true); });
    win->SetNavProvider([this]() { return m_nav; });
    win->Show(m_windows_visible);
    m_windows.push_back(win);
  }
  // More than one window would otherwise stack at the same spot; tile them so
  // each is reachable without dragging. Don't disturb the OpenCPN window here.
  if (m_windows.size() > 1) AutoLayoutWindows(/*reflow=*/false);
}

void mayara_pi::AutoLayoutWindows(bool reflow_ocpn) {
  if (m_windows.empty()) return;
  wxWindow* frame =
      m_parent_window ? wxGetTopLevelParent(m_parent_window) : nullptr;
  int disp = frame ? wxDisplay::GetFromWindow(frame) : wxNOT_FOUND;
  if (disp == wxNOT_FOUND) disp = 0;
  const wxRect area = wxDisplay(static_cast<unsigned>(disp)).GetClientArea();

  const int n = static_cast<int>(m_windows.size());
  const int radar_w = std::max(360, area.width * 38 / 100);
  if (reflow_ocpn && frame)
    frame->SetSize(area.x, area.y, area.width - radar_w, area.height);

  // Radar windows stacked down the right edge of the display.
  const int rx = area.x + area.width - radar_w;
  int y = area.y;
  for (int i = 0; i < n; ++i) {
    const int hh =
        (i == n - 1) ? (area.y + area.height - y) : (area.height / n);
    if (m_windows[i]) m_windows[i]->SetSize(rx, y, radar_w, hh);
    y += hh;
  }
}

void mayara_pi::TogglePpiWindow() {
  m_windows_visible = !AnyWindowShown();
  const int radar_count = m_client ? m_client->RadarCount() : 0;
  if (m_windows_visible &&
      (m_windows.empty() || m_windows_radar_count != radar_count))
    RebuildWindows();  // build, or rebuild for a changed radar set
  for (MayaraPpiWindow* win : m_windows)
    if (win) win->Show(m_windows_visible);
  SetToolbarItemState(m_tool_id, m_windows_visible);
}

bool mayara_pi::RenderGLOverlayMultiCanvas(wxGLContext* pcontext,
                                           PlugIn_ViewPort* vp, int canvasIndex,
                                           int priority) {
  if (!m_overlay_enabled || !m_client || !vp || !vp->bValid) return false;
  // OpenCPN calls this once per priority level per frame. Draw only at the
  // legacy chart-overlay layer; the higher passes (OVER_EMBOSS/OVER_UI) render
  // on top of the toolbar and chart bar, so drawing there paints over them.
  if (priority != OVERLAY_LEGACY) return false;
  const int n = m_client->RadarCount();
  if (n == 0) return false;
  if (static_cast<int>(m_overlay_tex.size()) != n)
    m_overlay_tex.assign(n, OverlayTex{});

  // Collect radars that have data, sorted by range descending so the longest
  // range is drawn first and the shortest composites on top (short-range inner
  // disc, longer-range annulus beyond it).
  struct Item {
    int idx;
    uint32_t range;
  };
  std::vector<Item> items;
  for (int i : m_client->ShownRadars()) {  // at most two displayed radars
    RadarState* st = m_client->StateAt(i);
    if (st && st->RangeMeters() > 0) items.push_back({i, st->RangeMeters()});
  }
  if (items.empty()) return false;
  std::sort(items.begin(), items.end(),
            [](const Item& a, const Item& b) { return a.range > b.range; });

  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  glEnable(GL_TEXTURE_2D);
  glColor4f(m_radar_intensity, m_radar_intensity, m_radar_intensity, 1.0f);

  // Each radar is drawn as an annulus from the next-shorter shown radar's range
  // out to its own range; the shortest is a full disc. So the shorter radar
  // occludes the longer one within its radius.
  bool drew = false;
  for (size_t k = 0; k < items.size(); ++k) {
    const double inner =
        (k + 1 < items.size())
            ? static_cast<double>(items[k + 1].range) / items[k].range
            : 0.0;
    if (DrawRadarOverlay(items[k].idx, vp, inner)) drew = true;
  }

  glBindTexture(GL_TEXTURE_2D, 0);
  glDisable(GL_TEXTURE_2D);
  glDisable(GL_BLEND);
  return drew;
}

bool mayara_pi::DrawRadarOverlay(int index, PlugIn_ViewPort* vp,
                                 double inner_frac) {
  RadarState* state = m_client->StateAt(index);
  if (!state) return false;
  const uint32_t range_m = state->RangeMeters();
  if (range_m == 0) return false;

  double lat = m_ownship_lat, lon = m_ownship_lon;
  if (lat == 0.0 && lon == 0.0)
    if (!state->Position(lat, lon)) return false;

  OverlayTex& t = m_overlay_tex[index];
  if (t.tex == 0) {
    glGenTextures(1, &t.tex);
    t.gen = ~0ull;
  }
  const uint64_t gen = state->Generation();
  if (gen != t.gen) {
    const int size = state->CopyDisc(m_overlay_disc);
    if (size <= 0) return false;
    glBindTexture(GL_TEXTURE_2D, t.tex);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, size, size, 0, GL_RGBA,
                 GL_UNSIGNED_BYTE, m_overlay_disc.data());
    t.gen = gen;
  }

  wxPoint center;
  GetCanvasPixLL(vp, &center, lat, lon);
  if (std::abs(center.x) > 1000000 || std::abs(center.y) > 1000000)
    return false;
  const double radius_px = range_m * vp->view_scale_ppm;
  if (radius_px < 1.0) return false;

  double heading = m_heading_true, sh = 0.0;
  if (heading == 0.0 && state->Heading(sh)) heading = sh;
  const double rot_deg = heading + vp->rotation * 180.0 / M_PI;

  glBindTexture(GL_TEXTURE_2D, t.tex);
  glPushMatrix();
  glTranslatef(center.x, center.y, 0.0f);
  glRotatef(rot_deg, 0.0f, 0.0f, 1.0f);
  glScalef(radius_px, radius_px, 1.0f);

  if (inner_frac <= 0.0) {
    // Full disc. Texcoord = (0.5 + 0.5*vertex).
    glBegin(GL_QUADS);
    glTexCoord2f(0.0f, 0.0f); glVertex2f(-1.0f, -1.0f);
    glTexCoord2f(1.0f, 0.0f); glVertex2f(1.0f, -1.0f);
    glTexCoord2f(1.0f, 1.0f); glVertex2f(1.0f, 1.0f);
    glTexCoord2f(0.0f, 1.0f); glVertex2f(-1.0f, 1.0f);
    glEnd();
  } else {
    // Annulus from inner_frac to 1.0 -- the inner circle is not drawn, so a
    // shorter-range radar occludes this one there.
    const int kSeg = 96;
    const double ri = std::min(0.999, inner_frac);
    glBegin(GL_TRIANGLE_STRIP);
    for (int i = 0; i <= kSeg; ++i) {
      const double a = 2.0 * M_PI * i / kSeg;
      const double c = std::cos(a), s = std::sin(a);
      const float ix = static_cast<float>(ri * c), iy = static_cast<float>(ri * s);
      const float ox = static_cast<float>(c), oy = static_cast<float>(s);
      glTexCoord2f(0.5f + 0.5f * ix, 0.5f + 0.5f * iy); glVertex2f(ix, iy);
      glTexCoord2f(0.5f + 0.5f * ox, 0.5f + 0.5f * oy); glVertex2f(ox, oy);
    }
    glEnd();
  }
  glPopMatrix();
  return true;
}

void mayara_pi::SetPositionFixEx(PlugIn_Position_Fix_Ex& pfix) {
  m_ownship_lat = pfix.Lat;
  m_ownship_lon = pfix.Lon;
  m_ownship_cog = pfix.Cog;
  m_heading_true = pfix.Hdt;

  // NaN-tolerant fill of the shared nav state for the PPI overlays.
  m_nav.lat = pfix.Lat;
  m_nav.lon = pfix.Lon;
  m_nav.valid = !std::isnan(pfix.Lat) && !std::isnan(pfix.Lon) &&
                (pfix.Lat != 0.0 || pfix.Lon != 0.0);
  m_nav.has_cog = !std::isnan(pfix.Cog) && pfix.Cog >= 0.0;
  m_nav.cog = m_nav.has_cog ? pfix.Cog : 0.0;
  m_nav.sog = std::isnan(pfix.Sog) ? 0.0 : pfix.Sog;
  m_nav.has_hdt = !std::isnan(pfix.Hdt) && pfix.Hdt >= 0.0 && pfix.Hdt < 360.0;
  m_nav.hdt = m_nav.has_hdt ? pfix.Hdt : 0.0;
}

void mayara_pi::SetColorScheme(PI_ColorScheme cs) {
  m_color_scheme = cs;
  const MayaraTheme t = ThemeFor(cs);
  m_radar_intensity = t.radar_intensity;
  if (m_client) m_client->SetAllIntensity(t.radar_intensity);
  ApplyThemeToWindows();
}
