/******************************************************************************
 * mayara_pi - OpenCPN plugin for mayara-server.
 *****************************************************************************/
#include "mayara_pi.h"

#include <cstdlib>

#include <wx/bmpbndl.h>
#include <wx/dcmemory.h>

#ifdef __WXOSX__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif

#include "MayaraClient.h"
#include "PpiWindow.h"
#include "RadarState.h"
#include "version.h"  // generated by FE2 from CMakeLists.txt values

// mayara-server is normally found via mDNS (it advertises _signalk-http._tcp).
// MAYARA_SERVER forces a specific address; kMayaraServerFallback is used only
// if discovery finds nothing.
static const char* kMayaraServerFallback = "http://10.56.0.1:6502";

static std::string MayaraExplicitUrl() {
  const char* env = std::getenv("MAYARA_SERVER");
  return (env && *env) ? std::string(env) : std::string();
}

// The two factory functions OpenCPN's PluginManager dlsym()s to load us.
extern "C" DECL_EXP opencpn_plugin* create_pi(void* ppimgr) {
  return new mayara_pi(ppimgr);
}

extern "C" DECL_EXP void destroy_pi(opencpn_plugin* p) { delete p; }

// Radar / PPI glyph with a transparent background and light strokes, matching
// the OpenCPN toolbar. Embedded and rasterized in-process so the plugin needs
// no shipped image files (and can be updated by replacing the .dylib alone).
static const char kRadarSvg[] =
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' "
    "stroke='#e8e8e8' stroke-width='1.6' stroke-linecap='round' "
    "stroke-linejoin='round'>"
    "<circle cx='12' cy='12' r='9.5'/>"
    "<circle cx='12' cy='12' r='6'/>"
    "<circle cx='12' cy='12' r='2.3'/>"
    "<path d='M12 12 L12 2.5 A9.5 9.5 0 0 1 20.4 7.2 Z' fill='#e8e8e8' "
    "fill-opacity='0.25' stroke='none'/>"
    "<line x1='12' y1='12' x2='12' y2='2.5'/>"
    "<circle cx='16' cy='8' r='1.1' fill='#e8e8e8' stroke='none'/>"
    "</svg>";

static wxBitmap RadarIcon(int px) {
  wxBitmapBundle bb = wxBitmapBundle::FromSVG(kRadarSvg, wxSize(px, px));
  if (bb.IsOk()) return bb.GetBitmap(wxSize(px, px));
  return wxBitmap(px, px, 32);  // transparent fallback
}

mayara_pi::mayara_pi(void* ppimgr) : opencpn_plugin_121(ppimgr) {
  m_panel_bitmap = RadarIcon(48);
  m_tool_bitmap = RadarIcon(32);
}

mayara_pi::~mayara_pi() = default;

int mayara_pi::Init() {
  m_parent_window = GetOCPNCanvasWindow();

  m_tool_id = InsertPlugInTool(
      _("Mayara"), &m_tool_bitmap, &m_tool_bitmap, wxITEM_CHECK,
      _("Mayara Radar"), _("Show or hide the Mayara radar PPI window"),
      nullptr, -1, 0, this);

  m_client = std::make_unique<MayaraClient>(MayaraExplicitUrl(),
                                            kMayaraServerFallback);
  m_client->Start();

  // Capabilities. The overlay callback is declared now but returns false until
  // Phase 1 wires up the spoke renderer.
  return WANTS_OPENGL_OVERLAY_CALLBACK | WANTS_OVERLAY_CALLBACK |
         WANTS_TOOLBAR_CALLBACK | INSTALLS_TOOLBAR_TOOL |
         WANTS_CURSOR_LATLON | USES_AUI_MANAGER;
}

bool mayara_pi::DeInit() {
  if (m_client) {
    m_client->Stop();
    m_client.reset();
  }
  if (m_ppi_window) {
    m_ppi_window->Destroy();
    m_ppi_window = nullptr;
  }
  if (m_tool_id != -1) {
    RemovePlugInTool(m_tool_id);
    m_tool_id = -1;
  }
  return true;
}

int mayara_pi::GetAPIVersionMajor() { return OCPN_API_VERSION_MAJOR; }
int mayara_pi::GetAPIVersionMinor() { return OCPN_API_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionMajor() { return PLUGIN_VERSION_MAJOR; }
int mayara_pi::GetPlugInVersionMinor() { return PLUGIN_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionPatch() { return PLUGIN_VERSION_PATCH; }

wxBitmap* mayara_pi::GetPlugInBitmap() { return &m_panel_bitmap; }

wxString mayara_pi::GetCommonName() { return _T("Mayara"); }

wxString mayara_pi::GetShortDescription() {
  return _("Marine radar overlay and PPI, served by mayara-server");
}

wxString mayara_pi::GetLongDescription() {
  return _(
      "mayara_pi displays marine radar as a chart overlay and in a PPI "
      "window. Unlike radar_pi it does not talk to radar hardware directly; "
      "it consumes the mayara-server REST and WebSocket API.");
}

int mayara_pi::GetToolbarToolCount() { return 1; }

void mayara_pi::OnToolbarToolCallback(int id) {
  if (id == m_tool_id) TogglePpiWindow();
}

void mayara_pi::TogglePpiWindow() {
  if (!m_ppi_window)
    m_ppi_window = new MayaraPpiWindow(m_parent_window, m_client.get());
  const bool show = !m_ppi_window->IsShown();
  m_ppi_window->Show(show);
  SetToolbarItemState(m_tool_id, show);
}

bool mayara_pi::RenderGLOverlayMultiCanvas(wxGLContext* pcontext,
                                           PlugIn_ViewPort* vp, int canvasIndex,
                                           int priority) {
  RadarState* state = m_client ? m_client->State() : nullptr;
  const uint32_t range_m = state ? state->RangeMeters() : 0;

  if (!m_client || !vp || !vp->bValid) return false;
  if (!state) return false;
  if (range_m == 0) return false;  // no radar data yet

  // Prefer OpenCPN's own-ship fix; fall back to the radar position stamped into
  // the spoke data when OpenCPN has no fix of its own.
  double lat = m_ownship_lat;
  double lon = m_ownship_lon;
  if (lat == 0.0 && lon == 0.0) {
    if (!state->Position(lat, lon)) return false;  // nowhere to place it
  }

  // Upload the cached disc as a texture, but only when it actually changed.
  const uint64_t gen = state->Generation();
  if (m_overlay_tex == 0) {
    glGenTextures(1, &m_overlay_tex);
    m_overlay_gen = ~0ull;
  }
  if (gen != m_overlay_gen) {
    m_overlay_size = state->CopyDisc(m_overlay_disc);
    if (m_overlay_size <= 0) return false;
    glBindTexture(GL_TEXTURE_2D, m_overlay_tex);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, m_overlay_size, m_overlay_size, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, m_overlay_disc.data());
    m_overlay_gen = gen;
  }
  if (m_overlay_size <= 0) return false;

  wxPoint center;
  GetCanvasPixLL(vp, &center, lat, lon);
  // GetCanvasPixLL can overflow to INT_MIN when the boat is far off this
  // viewport (e.g. a second canvas). Skip those.
  if (std::abs(center.x) > 1000000 || std::abs(center.y) > 1000000)
    return false;
  const double radius_px = range_m * vp->view_scale_ppm;
  if (radius_px < 1.0) return false;

  // Prefer OpenCPN's true heading; fall back to the heading carried in the
  // spoke data (bearing - angle) when OpenCPN has none. Disc is bow-up; rotate
  // to place the bow toward heading, plus the chart's own rotation.
  double heading = m_heading_true;
  double spoke_heading = 0.0;
  if (heading == 0.0 && state->Heading(spoke_heading)) heading = spoke_heading;
  const double rot_deg = heading + vp->rotation * 180.0 / M_PI;

  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  glEnable(GL_TEXTURE_2D);
  glBindTexture(GL_TEXTURE_2D, m_overlay_tex);
  glColor4f(1.0f, 1.0f, 1.0f, 1.0f);

  glPushMatrix();
  glTranslatef(center.x, center.y, 0.0f);
  glRotatef(rot_deg, 0.0f, 0.0f, 1.0f);
  glScalef(radius_px, radius_px, 1.0f);
  glBegin(GL_QUADS);
  glTexCoord2f(0.0f, 0.0f); glVertex2f(-1.0f, -1.0f);
  glTexCoord2f(1.0f, 0.0f); glVertex2f(1.0f, -1.0f);
  glTexCoord2f(1.0f, 1.0f); glVertex2f(1.0f, 1.0f);
  glTexCoord2f(0.0f, 1.0f); glVertex2f(-1.0f, 1.0f);
  glEnd();
  glPopMatrix();

  glBindTexture(GL_TEXTURE_2D, 0);
  glDisable(GL_TEXTURE_2D);
  glDisable(GL_BLEND);
  return true;
}

void mayara_pi::SetPositionFixEx(PlugIn_Position_Fix_Ex& pfix) {
  m_ownship_lat = pfix.Lat;
  m_ownship_lon = pfix.Lon;
  m_ownship_cog = pfix.Cog;
  m_heading_true = pfix.Hdt;
}

void mayara_pi::SetColorScheme(PI_ColorScheme cs) {}
