/******************************************************************************
 * mayara_pi - OpenCPN plugin for mayara-server.
 *****************************************************************************/
#include "mayara_pi.h"

#include <cstdlib>

#include <wx/bmpbndl.h>
#include <wx/dcmemory.h>

#include "MayaraClient.h"
#include "PpiWindow.h"
#include "version.h"  // generated by FE2 from CMakeLists.txt values

// Where mayara-server is expected. Overridable via the MAYARA_SERVER env var
// for development; proper mDNS/Bonjour discovery is a later (configuration)
// phase.
// TODO(config): discover mayara-server via mDNS instead of a fixed address.
static const char* kMayaraServerDefault = "http://10.56.0.1:6502";

static std::string MayaraServerUrl() {
  const char* env = std::getenv("MAYARA_SERVER");
  return (env && *env) ? std::string(env) : std::string(kMayaraServerDefault);
}

// The two factory functions OpenCPN's PluginManager dlsym()s to load us.
extern "C" DECL_EXP opencpn_plugin* create_pi(void* ppimgr) {
  return new mayara_pi(ppimgr);
}

extern "C" DECL_EXP void destroy_pi(opencpn_plugin* p) { delete p; }

// Radar / PPI glyph with a transparent background and light strokes, matching
// the OpenCPN toolbar. Embedded and rasterized in-process so the plugin needs
// no shipped image files (and can be updated by replacing the .dylib alone).
static const char kRadarSvg[] =
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' "
    "stroke='#e8e8e8' stroke-width='1.6' stroke-linecap='round' "
    "stroke-linejoin='round'>"
    "<circle cx='12' cy='12' r='9.5'/>"
    "<circle cx='12' cy='12' r='6'/>"
    "<circle cx='12' cy='12' r='2.3'/>"
    "<path d='M12 12 L12 2.5 A9.5 9.5 0 0 1 20.4 7.2 Z' fill='#e8e8e8' "
    "fill-opacity='0.25' stroke='none'/>"
    "<line x1='12' y1='12' x2='12' y2='2.5'/>"
    "<circle cx='16' cy='8' r='1.1' fill='#e8e8e8' stroke='none'/>"
    "</svg>";

static wxBitmap RadarIcon(int px) {
  wxBitmapBundle bb = wxBitmapBundle::FromSVG(kRadarSvg, wxSize(px, px));
  if (bb.IsOk()) return bb.GetBitmap(wxSize(px, px));
  return wxBitmap(px, px, 32);  // transparent fallback
}

mayara_pi::mayara_pi(void* ppimgr) : opencpn_plugin_121(ppimgr) {
  m_panel_bitmap = RadarIcon(48);
  m_tool_bitmap = RadarIcon(32);
}

mayara_pi::~mayara_pi() = default;

int mayara_pi::Init() {
  m_parent_window = GetOCPNCanvasWindow();

  m_tool_id = InsertPlugInTool(
      _("Mayara"), &m_tool_bitmap, &m_tool_bitmap, wxITEM_CHECK,
      _("Mayara Radar"), _("Show or hide the Mayara radar PPI window"),
      nullptr, -1, 0, this);

  m_client = std::make_unique<MayaraClient>(MayaraServerUrl());
  m_client->Start();

  // Capabilities. The overlay callback is declared now but returns false until
  // Phase 1 wires up the spoke renderer.
  return WANTS_OPENGL_OVERLAY_CALLBACK | WANTS_OVERLAY_CALLBACK |
         WANTS_TOOLBAR_CALLBACK | INSTALLS_TOOLBAR_TOOL |
         WANTS_CURSOR_LATLON | USES_AUI_MANAGER;
}

bool mayara_pi::DeInit() {
  if (m_client) {
    m_client->Stop();
    m_client.reset();
  }
  if (m_ppi_window) {
    m_ppi_window->Destroy();
    m_ppi_window = nullptr;
  }
  if (m_tool_id != -1) {
    RemovePlugInTool(m_tool_id);
    m_tool_id = -1;
  }
  return true;
}

int mayara_pi::GetAPIVersionMajor() { return OCPN_API_VERSION_MAJOR; }
int mayara_pi::GetAPIVersionMinor() { return OCPN_API_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionMajor() { return PLUGIN_VERSION_MAJOR; }
int mayara_pi::GetPlugInVersionMinor() { return PLUGIN_VERSION_MINOR; }
int mayara_pi::GetPlugInVersionPatch() { return PLUGIN_VERSION_PATCH; }

wxBitmap* mayara_pi::GetPlugInBitmap() { return &m_panel_bitmap; }

wxString mayara_pi::GetCommonName() { return _T("Mayara"); }

wxString mayara_pi::GetShortDescription() {
  return _("Marine radar overlay and PPI, served by mayara-server");
}

wxString mayara_pi::GetLongDescription() {
  return _(
      "mayara_pi displays marine radar as a chart overlay and in a PPI "
      "window. Unlike radar_pi it does not talk to radar hardware directly; "
      "it consumes the mayara-server REST and WebSocket API.");
}

int mayara_pi::GetToolbarToolCount() { return 1; }

void mayara_pi::OnToolbarToolCallback(int id) {
  if (id == m_tool_id) TogglePpiWindow();
}

void mayara_pi::TogglePpiWindow() {
  if (!m_ppi_window)
    m_ppi_window = new MayaraPpiWindow(m_parent_window, m_client.get());
  const bool show = !m_ppi_window->IsShown();
  m_ppi_window->Show(show);
  SetToolbarItemState(m_tool_id, show);
}

bool mayara_pi::RenderGLOverlayMultiCanvas(wxGLContext* pcontext,
                                           PlugIn_ViewPort* vp, int canvasIndex,
                                           int priority) {
  // Phase 1: draw server-supplied spokes here. Nothing to draw yet.
  return false;
}

void mayara_pi::SetPositionFixEx(PlugIn_Position_Fix_Ex& pfix) {
  m_ownship_lat = pfix.Lat;
  m_ownship_lon = pfix.Lon;
  m_ownship_cog = pfix.Cog;
  m_heading_true = pfix.Hdt;
}

void mayara_pi::SetColorScheme(PI_ColorScheme cs) {}
